import Foundation
import AgoraRtcKit
import Combine

/// Agora Voice SDK wrapper configured for audio-only calling.
final class AgoraService: NSObject, ObservableObject {

    // MARK: - Published Properties

    @Published var isInCall: Bool = false
    @Published var isMuted: Bool = false
    @Published var isSpeakerOn: Bool = true

    // MARK: - Closure

    /// Called when the remote user leaves the channel (e.g. hang-up or disconnect).
    var onRemoteUserLeft: (() -> Void)?

    // MARK: - Private Properties

    private var agoraKit: AgoraRtcEngineKit?

    // TODO: Replace with your Agora App ID from https://console.agora.io
    private let appId: String = "YOUR_AGORA_APP_ID"

    // MARK: - Init

    override init() {
        super.init()
        configureEngine()
    }

    deinit {
        AgoraRtcEngineKit.destroy()
    }

    // MARK: - Configuration

    /// Initializes the Agora engine with audio-only settings for 1:1 voice calls.
    private func configureEngine() {
        let config = AgoraRtcEngineConfig()
        config.appId = appId
        // TODO: If using a token server, set the channelProfile accordingly.

        agoraKit = AgoraRtcEngineKit.sharedEngine(with: config, delegate: self)

        // Audio-only configuration
        agoraKit?.setChannelProfile(.communication)
        agoraKit?.enableAudio()
        agoraKit?.disableVideo()

        // Default to speaker on for voice calls
        agoraKit?.setDefaultAudioRouteToSpeakerphone(true)
    }

    // MARK: - Channel Management

    /// Joins an Agora voice channel.
    /// - Parameters:
    ///   - token: Temporary token generated by the backend for this channel.
    ///   - channelId: The channel name to join.
    ///   - uid: The local user's numeric UID (0 lets Agora assign one automatically).
    func joinChannel(token: String, channelId: String, uid: UInt = 0) {
        let option = AgoraRtcChannelMediaOptions()
        option.publishMicrophoneTrack = true
        option.autoSubscribeAudio = true
        option.channelProfile = .communication

        agoraKit?.joinChannel(
            byToken: token,
            channelId: channelId,
            uid: uid,
            mediaOptions: option,
            joinSuccess: nil
        )
    }

    /// Leaves the current Agora voice channel and resets local state.
    func leaveChannel() {
        agoraKit?.leaveChannel(nil)
        DispatchQueue.main.async {
            self.isInCall = false
            self.isMuted = false
            self.isSpeakerOn = true
        }
    }

    // MARK: - Audio Controls

    /// Toggles the local microphone mute state.
    func toggleMute() {
        isMuted.toggle()
        agoraKit?.muteLocalAudioStream(isMuted)
    }

    /// Toggles between speaker and earpiece audio output.
    func toggleSpeaker() {
        isSpeakerOn.toggle()
        agoraKit?.setEnableSpeakerphone(isSpeakerOn)
    }
}

// MARK: - AgoraRtcEngineDelegate

extension AgoraService: AgoraRtcEngineDelegate {

    /// Called when the local user successfully joins a channel.
    func rtcEngine(_ engine: AgoraRtcEngineKit, didJoinChannel channel: String, withUid uid: UInt, elapsed: Int) {
        DispatchQueue.main.async {
            self.isInCall = true
        }
    }

    /// Called when the local user leaves a channel.
    func rtcEngine(_ engine: AgoraRtcEngineKit, didLeaveChannelWith stats: AgoraChannelStats) {
        DispatchQueue.main.async {
            self.isInCall = false
            self.isMuted = false
        }
    }

    /// Called when a remote user joins the channel.
    func rtcEngine(_ engine: AgoraRtcEngineKit, didJoinedOfUid uid: UInt, elapsed: Int) {
        // Remote peer has connected -- the call is now active with both parties.
    }

    /// Called when a remote user goes offline (leaves or loses connection).
    func rtcEngine(_ engine: AgoraRtcEngineKit, didOfflineOfUid uid: UInt, reason: AgoraUserOfflineReason) {
        DispatchQueue.main.async { [weak self] in
            self?.onRemoteUserLeft?()
        }
    }
}
